[versions]
kotlin = "2.2.20"
junit = "4.13.2"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin-lib = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
truth = "com.google.truth:truth:1.4.4"
rxjava = "io.reactivex.rxjava3:rxjava:3.1.11"
mockito = "com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0"
develocity-agent-adapters = "com.gradle:develocity-gradle-plugin-adapters:1.2.1"
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

[plugins]
kgp = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version = "0.52.0" }
kotlinter = { id = "org.jmailen.kotlinter", version = "5.2.0" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.34.0" }

