[versions]
kotlin = "2.0.20"
junit = "4.13.2"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin-lib = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
truth = "com.google.truth:truth:1.4.4"
rxjava = "io.reactivex.rxjava3:rxjava:3.1.9"
mockito = "com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0"
okio = "com.squareup.okio:okio:3.9.0"
develocity-agent-adapters = "com.gradle:develocity-gradle-plugin-adapters:1.0.2"

[plugins]
kgp = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.4.1" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }

