[versions]
kotlin = "2.1.21"
junit = "4.13.2"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin-lib = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
truth = "com.google.truth:truth:1.4.4"
rxjava = "io.reactivex.rxjava3:rxjava:3.1.10"
mockito = "com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0"
okio = "com.squareup.okio:okio:3.11.0"
develocity-agent-adapters = "com.gradle:develocity-gradle-plugin-adapters:1.2.1"

[plugins]
kgp = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version = "0.52.0" }
kotlinter = { id = "org.jmailen.kotlinter", version = "5.0.1" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }

