[versions]
kotlin = "1.9.21"
junit = "4.13.2"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin-lib = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
truth = "com.google.truth:truth:1.2.0"
tagger = "com.osacky.tagger:tagger-lib:0.2"
rxjava = "io.reactivex.rxjava3:rxjava:3.1.8"
mockito = "com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0"

[plugins]
kgp = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versions = { id = "com.github.ben-manes.versions", version = "0.50.0" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.1.0" }
plugin-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }

